spring:
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      temp:
        use_jdbc_metadata_defaults: false
      id:
        new_generator_mappings: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  thymeleaf:
    encoding: UTF-8
  flyway:
    baseline-on-migrate: true
server:
  port: 8085